import { useState } from "react";

export const thesaurusJson = {
  "Abstract Relations": {
    Existence: {
      abstract: [
        { name: "existence", number: 1 },
        { name: "inexistence", number: 2 },
      ],
      concrete: [
        { name: "substantiality", number: 3 },
        { name: "unsubstantiality", number: 4 },
      ],
      formal: [
        { name: "intrinsicality", number: 5 },
        { name: "extrinsicality", number: 6 },
      ],
      modal: [
        { name: "state", number: 7 },
        { name: "circumstance", number: 8 },
      ],
    },
    Relation: {
      absolute: [
        { name: "relation", number: 9 },
        { name: "irrelation", number: 10 },
        { name: "consanguinity", number: 11 },
        { name: "correlation", number: 12 },
        { name: "identity", number: 13 },
        { name: "contrariety", number: 14 },
        { name: "difference", number: 15 },
      ],
      continious: [
        { name: "uniformity", number: 16 },
        { name: "non-uniformity", number: 17 },
      ],
      partial: [
        { name: "similarity", number: 18 },
        { name: "dissimilarity", number: 19 },
        { name: "imitation", number: 20 },
        { name: "non-imitation", number: 21 },
        { name: "variation", number: 22 },
        { name: "copy", number: 23 },
        { name: "prototype", number: 24 },
      ],
      general: [
        { name: "agreement", number: 25 },
        { name: "disagreement", number: 26 },
      ],
    },
    Quantity: {
      simple: [
        { name: "quantity", number: 27 },
        { name: "degree", number: 28 },
        { name: "equality", number: 29 },
        { name: "inequality", number: 30 },
      ],
      comparative: [
        { name: "mean", number: 31 },
        { name: "compensation", number: 32 },
        { name: "greatness", number: 33 },
        { name: "smallness", number: 34 },
        { name: "superiority", number: 35 },
        { name: "inferiority", number: 36 },
        { name: "increase", number: 37 },
        { name: "decrease", number: 38 },
      ],
      conjunctive: [
        { name: "addition", number: 39 },
        { name: "non-addition", number: 40 },
        { name: "subduction", number: 41 },
        { name: "adjunct", number: 42 },
        { name: "remainder", number: 43 },
        { name: "mixture", number: 44 },
        { name: "simpleness", number: 45 },
        { name: "junction", number: 46 },
        { name: "disjunction", number: 47 },
        { name: "vinculum", number: 48 },
        { name: "coherence", number: 49 },
        { name: "incoherence", number: 50 },
        { name: "combination", number: 51 },
        { name: "decomposition", number: 52 },
      ],
      concrete: [
        { name: "whole", number: 53 },
        { name: "part", number: 54 },
        { name: "completeness", number: 55 },
        { name: "incompleteness", number: 56 },
        { name: "composition", number: 57 },
        { name: "exclusion", number: 58 },
        { name: "component", number: 59 },
        { name: "extranseous", number: 60 },
      ],
    },
    Order: {
      general: [
        { name: "order", number: 61 },
        { name: "disorder", number: 62 },
        { name: "arrangement", number: 63 },
        { name: "derangement", number: 64 },
      ],
      consecutive: [
        { name: "precedence", number: 65 },
        { name: "sequence", number: 66 },
        { name: "precursor", number: 67 },
        { name: "sequel", number: 68 },
        { name: "beginning", number: 69 },
        { name: "end", number: 70 },
        { name: "middle", number: 71 },
        { name: "continuity", number: 72 },
        { name: "discontinuity", number: 73 },
        { name: "term", number: 74 },
      ],
      collective: [
        { name: "assemblage", number: 75 },
        { name: "dispersion", number: 76 },
        { name: "focus", number: 77 },
        { name: "class", number: 78 },
      ],
      distributive: [
        { name: "class", number: 79 },
        { name: "inclusion", number: 80 },
        { name: "exclusion", number: 81 },
        { name: "generality", number: 82 },
        { name: "speciality", number: 83 },
      ],
      categorical: [
        { name: "rule", number: 84 },
        { name: "multiformity", number: 85 },
        { name: "confirmity", number: 86 },
        { name: "unconformity", number: 87 },
      ],
    },
    Number: {
      abstract: [
        { name: "number", number: 88 },
        { name: "numeration", number: 89 },
        { name: "list", number: 88 },
      ],
      determinate: [
        { name: "unity", number: 89 },
        { name: "duality", number: 90 },
        { name: "accompaniment", number: 91 },
        { name: "duplication", number: 92 },
        { name: "bisection", number: 93 },
        { name: "triplication", number: 94 },
        { name: "trisection", number: 95 },
        { name: "quadruplication", number: 96 },
        { name: "quaternity", number: 97 },
        { name: "quadrisection", number: 98 },
        { name: "five", number: 99 },
        { name: "quinquesection", number: 100 },
        { name: "number", number: 101 },
      ],
      indeterminate: [
        { name: "plurality", number: 102 },
        { name: "zero", number: 102 },
        { name: "multitude", number: 103 },
        { name: "fewness", number: 104 },
        { name: "repetition", number: 105 },
        { name: "infinity", number: 106 },
      ],
    },
    Time: {
      absolute: [
        { name: "time", number: 107 },
        { name: "neverness", number: 108 },
        { name: "period", number: 109 },
        { name: "course", number: 110 },
        { name: "contingent duration", number: 111 },
        { name: "diuturnity", number: 112 },
        { name: "transientness", number: 113 },
        { name: "perpetuity", number: 114 },
        { name: "instantaneity", number: 115 },
        { name: "chronometry", number: 116 },
        { name: "anachromism", number: 117 },
      ],
      relative: [
        { name: "priority", number: 118 },
        { name: "posteriority", number: 119 },
        { name: "present time", number: 120 },
        { name: "different time", number: 121 },
        { name: "synchronism", number: 122 },
        { name: "futurity", number: 123 },
        { name: "preterition", number: 124 },
        { name: "newness", number: 125 },
        { name: "oldness", number: 126 },
        { name: "morning", number: 127 },
        { name: "evening", number: 128 },
        { name: "youth", number: 129 },
        { name: "age", number: 130 },
        { name: "infant", number: 131 },
        { name: "adolescence", number: 132 },
        { name: "earliness", number: 133 },
        { name: "lateness", number: 134 },
        { name: "occasion", number: 135 },
        { name: "intempestivity", number: 136 },
      ],
      recurrent: [
        { name: "frequency", number: 137 },
        { name: "infrequency", number: 138 },
        { name: "periodicity", number: 139 },
      ],
      simple: [
        { name: "change", number: 140 },
        { name: "permanence", number: 141 },
        { name: "cessation", number: 142 },
        { name: "continuance", number: 143 },
        { name: "conversion", number: 144 },
        { name: "reversion", number: 145 },
        { name: "revolution", number: 146 },
        { name: "substitution", number: 147 },
        { name: "interchange", number: 148 },
      ],
      complex: [
        { name: "changeableness", number: 149 },
        { name: "stability", number: 150 },
        { name: "eventuallity", number: 151 },
        { name: "destiny", number: 152 },
      ],
    },
    Causation: {
      "constancy of sequence": [
        { name: "cause", number: 153 },
        { name: "effect", number: 154 },
        { name: "attribution", number: 153 },
        { name: "chance", number: 154 },
      ],
      "connection between cause and effect": [
        { name: "power", number: 155 },
        { name: "impotence", number: 156 },
        { name: "strength", number: 157 },
        { name: "weakness", number: 158 },
      ],
      "power in operation": [
        { name: "production", number: 159 },
        { name: "destruction", number: 160 },
        { name: "reproduction", number: 161 },
        { name: "producer", number: 162 },
        { name: "destroyer", number: 163 },
        { name: "paternity", number: 164 },
        { name: "posterity", number: 165 },
        { name: "productiveness", number: 166 },
        { name: "unproductiveness", number: 167 },
        { name: "agency", number: 168 },
        { name: "energy", number: 169 },
        { name: "inertness", number: 170 },
        { name: "violence", number: 171 },
        { name: "moderation", number: 172 },
      ],
      "indirect power": [
        { name: "influence", number: 173 },
        { name: "absence of influence", number: 174 },
        { name: "tendency", number: 175 },
        { name: "liability", number: 176 },
      ],
      "combination of causes": [
        { name: "concurrence", number: 177 },
        { name: "counteraction", number: 178 },
      ],
    },
  },
  Space: {
    "space in general": {
      "abstract space": [
        { name: "space", number: 179 },
        { name: "inextension", number: 180 },
        { name: "region", number: 181 },
        { name: "place", number: 182 },
      ],
      "relative space": [
        { name: "situation", number: 182 },
        { name: "location", number: 183 },
        { name: "displacement", number: 184 },
      ],
      "existence in space": [
        { name: "presence", number: 185 },
        { name: "absence", number: 185 },
        { name: "inhabitant", number: 186 },
        { name: "abode", number: 187 },
        { name: "contents", number: 188 },
        { name: "receptacle", number: 189 },
      ],
    },
    dimensions: {
      general: [
        { name: "size", number: 190 },
        { name: "littleness", number: 191 },
        { name: "expansion", number: 192 },
        { name: "contraction", number: 193 },
        { name: "distance", number: 194 },
        { name: "nearness", number: 195 },
        { name: "interval", number: 196 },
        { name: "contiguity", number: 197 },
      ],
      linear: [
        { name: "length", number: 198 },
        { name: "shortness", number: 199 },
        { name: "breadth", number: 200 },
        { name: "thickness", number: 200 },
        { name: "thinness", number: 201 },
        { name: "layer", number: 202 },
        { name: "filament", number: 203 },
        { name: "height", number: 204 },
        { name: "lowness", number: 205 },
        { name: "depth", number: 206 },
        { name: "shallowness", number: 207 },
        { name: "summit", number: 208 },
        { name: "base", number: 209 },
        { name: "verticality", number: 210 },
        { name: "horizontality", number: 211 },
        { name: "pendency", number: 212 },
        { name: "support", number: 213 },
        { name: "parallelism", number: 214 },
        { name: "obliquity", number: 215 },
        { name: "inversion", number: 216 },
        { name: "crossing", number: 217 },
      ],
      centrality: [
        { name: "exteriority", number: 218 },
        { name: "interiority", number: 219 },
        { name: "centrality", number: 220 },
        { name: "covering", number: 221 },
        { name: "lining", number: 222 },
        { name: "investment", number: 223 },
        { name: "divestment", number: 224 },
        { name: "circumjacence", number: 225 },
        { name: "interjacence", number: 226 },
        { name: "circumscription", number: 227 },
        { name: "outline", number: 228 },
        { name: "edge", number: 229 },
        { name: "inclosure", number: 230 },
        { name: "limit", number: 231 },
        { name: "front", number: 232 },
        { name: "rear", number: 233 },
        { name: "laterality", number: 234 },
        { name: "contraposition", number: 235 },
        { name: "dextrality", number: 236 },
        { name: "sinistrality", number: 237 },
      ],
    },
    form: {
      general: [
        { name: "form", number: 238 },
        { name: "amorphism", number: 239 },
        { name: "symmetry", number: 240 },
        { name: "distortion", number: 241 },
      ],
      special: [
        { name: "angularity", number: 242 },
        { name: "curvature", number: 243 },
        { name: "circularity", number: 244 },
        { name: "convolution", number: 245 },
        { name: "rotundity", number: 246 },
      ],
      superficial: [
        { name: "convexity", number: 247 },
        { name: "concavity", number: 248 },
        { name: "flatness", number: 249 },
        { name: "sharpness", number: 250 },
        { name: "bluntness", number: 251 },
        { name: "smsoothness", number: 252 },
        { name: "roughness", number: 253 },
        { name: "notch", number: 254 },
        { name: "fold", number: 255 },
        { name: "furrow", number: 256 },
        { name: "opening", number: 257 },
        { name: "closure", number: 258 },
        { name: "perforator", number: 259 },
        { name: "stopper", number: 260 },
      ],
    },
    motion: {
      "motion in general": [
        { name: "motion", number: 261 },
        { name: "quiescence", number: 262 },
        { name: "journey", number: 263 },
        { name: "navigation", number: 264 },
        { name: "traveller", number: 265 },
        { name: "mariner", number: 266 },
        { name: "transference", number: 267 },
        { name: "carrier", number: 268 },
        { name: "vehicle", number: 269 },
        { name: "ship", number: 270 },
        { name: "velocity", number: 271 },
      ],
      "degrees of motion": [
        { name: "slowness", number: 272 },
        { name: "flatness", number: 273 },
      ],
      "conjoined with force": [
        { name: "impulse", number: 274 },
        { name: "recoil", number: 275 },
      ],
      "with reference to direction": [
        { name: "direction", number: 276 },
        { name: "deviation", number: 277 },
        { name: "precession", number: 278 },
        { name: "sequence", number: 279 },
        { name: "propulsion", number: 280 },
        { name: "traction", number: 281 },
        { name: "approach", number: 282 },
        { name: "recession", number: 283 },
        { name: "attraction", number: 284 },
        { name: "repulsion", number: 285 },
        { name: "convergence", number: 286 },
        { name: "divergence", number: 287 },
        { name: "arrival", number: 288 },
        { name: "departure", number: 289 },
        { name: "ingress", number: 290 },
        { name: "egress", number: 291 },
        { name: "reception", number: 292 },
        { name: "ejection", number: 293 },
        { name: "food", number: 294 },
        { name: "excretion", number: 295 },
        { name: "insertion", number: 296 },
        { name: "extraction", number: 297 },
        { name: "passage", number: 298 },
        { name: "overstep", number: 299 },
        { name: "shortcoming", number: 300 },
        { name: "ascent", number: 301 },
        { name: "descent", number: 302 },
        { name: "elevation", number: 303 },
        { name: "depression", number: 304 },
        { name: "leap", number: 305 },
        { name: "circuition", number: 306 },
        { name: "rotation", number: 307 },
        { name: "evolution", number: 308 },
        { name: "agitation", number: 309 },
      ],
    },
  },
  Matter: {
    "matter in general": {
      materiality: [
        { name: "materiality", number: 310 },
        { name: "immateriality", number: 311 },
        { name: "world", number: 312 },
        { name: "gravity", number: 313 },
        { name: "levity", number: 314 },
      ],
    },
    "inorganic matter": {
      solids: [
        { name: "density", number: 315 },
        { name: "rarity", number: 316 },
        { name: "hardness", number: 317 },
        { name: "softness", number: 318 },
        { name: "elasticity", number: 319 },
        { name: "inelasticity", number: 320 },
        { name: "tenacity", number: 321 },
        { name: "brittleness", number: 322 },
        { name: "texture", number: 323 },
        { name: "pulverulence", number: 324 },
        { name: "friction", number: 325 },
        { name: "lubrication", number: 326 },
      ],
      fluids: [
        { name: "fluidity", number: 327 },
        { name: "gaseity", number: 328 },
        { name: "liquefaction", number: 329 },
        { name: "vaporization", number: 330 },
        { name: "water", number: 331 },
        { name: "air", number: 332 },
        { name: "moisture", number: 333 },
        { name: "dryness", number: 334 },
        { name: "ocean", number: 335 },
        { name: "land", number: 336 },
        { name: "lake", number: 337 },
        { name: "plain", number: 338 },
        { name: "marsh", number: 339 },
        { name: "island", number: 340 },
        { name: "stream", number: 341 },
        { name: "river", number: 342 },
        { name: "wind", number: 343 },
        { name: "conduit", number: 344 },
        { name: "air-pipe", number: 345 },
      ],
      "imperfect fluid": [
        { name: "semiliquidity", number: 352 },
        { name: "bubble", number: 353 },
        { name: "pulpiness", number: 354 },
        { name: "unctuosness", number: 355 },
        { name: "oil", number: 356 },
        { name: "resin", number: 357 },
      ],
    },
    "organic matter": {
      vitality: [
        { name: "organization", number: 358 },
        { name: "inorganization", number: 359 },
        { name: "life", number: 360 },
        { name: "death", number: 361 },
        { name: "killing", number: 362 },
        { name: "corpse", number: 363 },
        { name: "interment", number: 364 },
        { name: "animality", number: 365 },
        { name: "vegetability", number: 366 },
        { name: "animal", number: 367 },
        { name: "vegetable", number: 368 },
        { name: "zoology", number: 370 },
        { name: "botany", number: 371 },
        { name: "circuration", number: 372 },
        { name: "agriculture", number: 373 },
        { name: "mankind", number: 374 },
        { name: "man", number: 375 },
        { name: "woman", number: 376 },
      ],
      "sensation: general": [
        { name: "sensibility", number: 377 },
        { name: "insensibility", number: 378 },
        { name: "pleasure", number: 379 },
        { name: "pain", number: 380 },
      ],
      "sensation: touch": [
        { name: "touch", number: 381 },
        { name: "numbness", number: 382 },
      ],
      "sensation: heat": [
        { name: "heat", number: 383 },
        { name: "cold", number: 384 },
        { name: "calefaction", number: 385 },
        { name: "refrigeration", number: 386 },
        { name: "furnace", number: 387 },
        { name: "refrigeratory", number: 388 },
        { name: "fuel", number: 389 },
        { name: "thermometer", number: 390 },
      ],
      "sensation: taste": [
        { name: "taste", number: 391 },
        { name: "insipidity", number: 392 },
        { name: "pungency", number: 393 },
        { name: "condiment", number: 394 },
        { name: "savouriness", number: 395 },
        { name: "unsavouriness", number: 396 },
        { name: "sweetness", number: 397 },
        { name: "sourness", number: 398 },
      ],
      "sensation: odour": [
        { name: "odour", number: 399 },
        { name: "inodorousness", number: 400 },
        { name: "fragrance", number: 401 },
        { name: "foetor", number: 402 },
      ],
      "sensation: sound": [
        { name: "sound", number: 403 },
        { name: "silence", number: 404 },
        { name: "loudness", number: 405 },
        { name: "faintness", number: 406 },
        { name: "snap", number: 407 },
        { name: "roll", number: 408 },
        { name: "resonance", number: 409 },
        { name: "non-resonance", number: 410 },
        { name: "stridor", number: 411 },
        { name: "cry", number: 412 },
        { name: "sibilation", number: 413 },
        { name: "ululation", number: 414 },
        { name: "melody", number: 415 },
        { name: "discord", number: 416 },
        { name: "music", number: 417 },
        { name: "musician", number: 418 },
        { name: "musical instruments", number: 419 },
        { name: "hearing", number: 420 },
        { name: "deafness", number: 421 },
      ],
      "sensation: light": [
        { name: "light", number: 422 },
        { name: "darkness", number: 423 },
        { name: "dimness", number: 424 },
        { name: "luminary", number: 425 },
        { name: "shade", number: 426 },
        { name: "transparency", number: 427 },
        { name: "opacity", number: 428 },
        { name: "semitransparency", number: 429 },
        { name: "colour", number: 430 },
        { name: "achromatism", number: 431 },
        { name: "whiteness", number: 432 },
        { name: "blackness", number: 433 },
        { name: "gray", number: 434 },
        { name: "brown", number: 435 },
        { name: "redness", number: 436 },
        { name: "greenness", number: 437 },
        { name: "yellowness", number: 438 },
        { name: "purple", number: 439 },
        { name: "blueness", number: 440 },
        { name: "orange", number: 441 },
        { name: "variegation", number: 442 },
        { name: "vision", number: 443 },
        { name: "blindness", number: 444 },
        { name: "dimsightedness", number: 445 },
        { name: "spectator", number: 446 },
        { name: "optical instruments", number: 447 },
        { name: "visibility", number: 448 },
        { name: "invisibility", number: 449 },
        { name: "appearance", number: 450 },
        { name: "disappearance", number: 451 },
      ],
    },
  },
  Intellect: {
    "formation of ideas": {
      "operations of intellect in general": [
        { name: "intellect", number: 452 },
        { name: "absence of intellect", number: 453 },
        { name: "thought", number: 454 },
        { name: "incogitancy", number: 455 },
      ],
      "precursory conditions and operations": [
        { name: "idea", number: 456 },
        { name: "topic", number: 457 },
        { name: "curiosity", number: 458 },
        { name: "incuriosity", number: 459 },
        { name: "attention", number: 460 },
        { name: "inattention", number: 461 },
        { name: "care", number: 462 },
        { name: "neglect", number: 463 },
        { name: "inquiry", number: 464 },
        { name: "answer", number: 465 },
        { name: "experiment", number: 466 },
        { name: "comparison", number: 467 },
        { name: "discrimination", number: 468 },
        { name: "indiscrimination", number: 460 },
        { name: "measurement", number: 461 },
      ],
      "materials for reasoning": [
        { name: "evidence", number: 462 },
        { name: "counter-evidence", number: 463 },
        { name: "qualification", number: 464 },
        { name: "possibility", number: 465 },
        { name: "impossibility", number: 466 },
        { name: "probability", number: 467 },
        { name: "improbability", number: 468 },
        { name: "certainty", number: 469 },
        { name: "uncertainty", number: 470 },
      ],
      "reasoning of processes": [
        { name: "reasoning", number: 471 },
        { name: "intuition", number: 472 },
        { name: "demonstration", number: 473 },
        { name: "confutation", number: 474 },
      ],
      "results of reasoning": [
        { name: "judgement", number: 475 },
        { name: "midjudgement", number: 476 },
        { name: "discovery", number: 477 },
        { name: "overestimation", number: 478 },
        { name: "underestimation", number: 479 },
        { name: "belief", number: 480 },
        { name: "doubt", number: 481 },
        { name: "credulity", number: 482 },
        { name: "incredulity", number: 483 },
        { name: "assent", number: 484 },
        { name: "dissent", number: 485 },
        { name: "knowledge", number: 486 },
        { name: "ignorance", number: 487 },
        { name: "scholar", number: 488 },
        { name: "ignoramous", number: 489 },
        { name: "truth", number: 490 },
        { name: "error", number: 491 },
        { name: "maxim", number: 492 },
        { name: "absurdity", number: 493 },
        { name: "intelligence", number: 494 },
        { name: "folly", number: 495 },
        { name: "sage", number: 496 },
        { name: "fool", number: 497 },
        { name: "sanity", number: 498 },
        { name: "insanity", number: 499 },
        { name: "madman", number: 500 },
      ],
      "extension of though": [
        { name: "memory", number: 501 },
        { name: "oblivion", number: 502 },
        { name: "expectation", number: 503 },
        { name: "inexpectation", number: 504 },
        { name: "disappointment", number: 505 },
        { name: "foresight", number: 506 },
        { name: "omen", number: 507 },
        { name: "oracle", number: 508 },
      ],
      "creative thoughts": [
        { name: "supposition", number: 509 },
        { name: "imagination", number: 510 },
      ],
    },
    "communication of ideas": {
      "nature of ideas communicated": [
        { name: "meaning", number: 511 },
        { name: "unmeaningness", number: 512 },
        { name: "intelligibility", number: 513 },
        { name: "unintelligiblity", number: 514 },
        { name: "equivocalness", number: 515 },
        { name: "metaphor", number: 516 },
        { name: "interpretation", number: 517 },
        { name: "misinterpretation", number: 518 },
        { name: "interpreter", number: 519 },
      ],
      "modes of communicaiton": [
        { name: "manifestation", number: 520 },
        { name: "latency", number: 530 },
        { name: "information", number: 531 },
        { name: "concealment", number: 532 },
        { name: "disclosure", number: 533 },
        { name: "ambush", number: 534 },
        { name: "publication", number: 535 },
        { name: "news", number: 536 },
        { name: "secret", number: 537 },
        { name: "messenger", number: 538 },
        { name: "affirmation", number: 539 },
        { name: "negation", number: 540 },
        { name: "teaching", number: 541 },
        { name: "misteaching", number: 542 },
        { name: "teacher", number: 543 },
        { name: "learning", number: 544 },
        { name: "learner", number: 545 },
        { name: "school", number: 546 },
        { name: "veracity", number: 547 },
        { name: "falsehood", number: 548 },
        { name: "deception", number: 549 },
        { name: "untruth", number: 550 },
        { name: "dupe", number: 551 },
        { name: "deceiver", number: 552 },
        { name: "exaggeration", number: 553 },
      ],
      "means of communication": [
        { name: "indication", number: 533 },
        { name: "record", number: 534 },
        { name: "obliteration", number: 535 },
        { name: "recorder", number: 536 },
        { name: "representation", number: 537 },
        { name: "misrepresentation", number: 538 },
        { name: "painting", number: 539 },
        { name: "sculpture", number: 540 },
        { name: "engraving", number: 541 },
        { name: "artist", number: 542 },
        { name: "language", number: 543 },
        { name: "letter", number: 544 },
        { name: "word", number: 545 },
        { name: "neology", number: 546 },
        { name: "nomenclature", number: 547 },
        { name: "misnomer", number: 548 },
        { name: "phrase", number: 549 },
        { name: "grammar", number: 550 },
        { name: "solecism", number: 551 },
        { name: "style", number: 552 },
        { name: "perpicuity", number: 553 },
        { name: "obscurity", number: 554 },
        { name: "conciseness", number: 555 },
        { name: "diffuseness", number: 556 },
        { name: "vigour", number: 557 },
        { name: "feebleness", number: 558 },
        { name: "plainness", number: 559 },
        { name: "ornament", number: 560 },
        { name: "elegance", number: 561 },
        { name: "inelegence", number: 562 },
        { name: "voice", number: 563 },
        { name: "aphony", number: 564 },
        { name: "speech", number: 565 },
        { name: "stammering", number: 566 },
        { name: "loquacity", number: 567 },
        { name: "taciturnity", number: 568 },
        { name: "allocution", number: 569 },
        { name: "response", number: 570 },
        { name: "interlocution", number: 571 },
        { name: "soliloquy", number: 572 },
        { name: "writing", number: 573 },
        { name: "printing", number: 574 },
        { name: "correspondence", number: 575 },
        { name: "book", number: 576 },
        { name: "description", number: 577 },
        { name: "dissertation", number: 578 },
        { name: "compendium", number: 579 },
        { name: "poetry", number: 580 },
        { name: "prose", number: 581 },
        { name: "the drama", number: 582 },
      ],
    },
  },
  Volition: {
    "individual volition": {
      "volition in general": [
        { name: "will", number: 583 },
        { name: "necessity", number: 584 },
        { name: "willingness", number: 585 },
        { name: "unwillingness", number: 586 },
        { name: "resolution", number: 587 },
        { name: "irresolution", number: 588 },
        { name: "perserverance", number: 589 },
        { name: "obstinacy", number: 590 },
        { name: "tergiversation", number: 591 },
        { name: "caprice", number: 592 },
        { name: "choice", number: 593 },
        { name: "absence of choice", number: 594 },
        { name: "rejection", number: 595 },
        { name: "predetermination", number: 596 },
        { name: "impulse", number: 597 },
        { name: "habit", number: 598 },
        { name: "desuetude", number: 599 },
        { name: "motive", number: 600 },
        { name: "absence of motive", number: 601 },
        { name: "dissuasion", number: 602 },
        { name: "plea", number: 603 },
        { name: "good", number: 604 },
        { name: "evil", number: 605 },
      ],
      "prospective volition": [
        { name: "intention", number: 606 },
        { name: "chance", number: 607 },
        { name: "pursuit", number: 608 },
        { name: "avoidance", number: 609 },
        { name: "relinquishment", number: 610 },
        { name: "business", number: 611 },
        { name: "plan", number: 612 },
        { name: "method", number: 613 },
        { name: "mid-course", number: 614 },
        { name: "circuit", number: 615 },
        { name: "requirement", number: 616 },
        { name: "instrumentality", number: 617 },
        { name: "means", number: 618 },
        { name: "instrument", number: 619 },
        { name: "substitute", number: 620 },
        { name: "materials", number: 621 },
        { name: "store", number: 622 },
        { name: "provision", number: 623 },
        { name: "waste", number: 624 },
        { name: "sufficiency", number: 625 },
        { name: "insufficiency", number: 636 },
        { name: "redundance", number: 637 },
        { name: "importance", number: 638 },
        { name: "unimportance", number: 639 },
        { name: "utility", number: 640 },
        { name: "inutility", number: 641 },
        { name: "expedience", number: 642 },
        { name: "inexpedience", number: 643 },
        { name: "goodness", number: 644 },
        { name: "badness", number: 645 },
        { name: "perfection", number: 646 },
        { name: "imperfection", number: 647 },
        { name: "cleanness", number: 648 },
        { name: "uncleanness", number: 649 },
        { name: "health", number: 650 },
        { name: "disease", number: 651 },
        { name: "salubrity", number: 652 },
        { name: "insalubrity", number: 653 },
        { name: "improvement", number: 654 },
        { name: "deterioration", number: 655 },
        { name: "restoration", number: 656 },
        { name: "relapse", number: 657 },
        { name: "remedy", number: 658 },
        { name: "bane", number: 659 },
        { name: "safety", number: 660 },
        { name: "danger", number: 661 },
        { name: "refuge", number: 662 },
        { name: "pitfall", number: 663 },
        { name: "warning", number: 664 },
        { name: "alarm", number: 665 },
        { name: "preservation", number: 666 },
        { name: "escape", number: 667 },
        { name: "deliverance", number: 668 },
        { name: "perparation", number: 669 },
        { name: "non-preparation", number: 670 },
        { name: "essay", number: 671 },
        { name: "undertaking", number: 672 },
        { name: "use", number: 673 },
        { name: "disuse", number: 674 },
        { name: "misuse", number: 675 },
        { name: "action", number: 676 },
        { name: "inaction", number: 677 },
        { name: "haste", number: 678 },
        { name: "leisure", number: 679 },
        { name: "exertion", number: 680 },
        { name: "repose", number: 681 },
        { name: "fatigue", number: 682 },
        { name: "refreshment", number: 683 },
        { name: "agent", number: 684 },
        { name: "workshop", number: 685 },
        { name: "conduct", number: 686 },
        { name: "direction", number: 687 },
        { name: "director", number: 688 },
        { name: "advice", number: 689 },
        { name: "council", number: 690 },
        { name: "precept", number: 691 },
        { name: "skill", number: 692 },
        { name: "unskillfulness", number: 693 },
        { name: "proficient", number: 694 },
        { name: "bungler", number: 695 },
        { name: "cunning", number: 696 },
        { name: "artlessness", number: 697 },
        { name: "difficulty", number: 698 },
        { name: "facility", number: 699 },
        { name: "hindrance", number: 700 },
        { name: "aid", number: 701 },
        { name: "opposition", number: 702 },
        { name: "co-operation", number: 703 },
        { name: "opponent", number: 704 },
        { name: "auxiliary", number: 705 },
        { name: "party", number: 706 },
        { name: "discord", number: 707 },
        { name: "concord", number: 708 },
        { name: "attack", number: 709 },
        { name: "defence", number: 710 },
        { name: "retaliation", number: 711 },
        { name: "resistance", number: 712 },
        { name: "contention", number: 713 },
        { name: "peace", number: 714 },
        { name: "warfare", number: 715 },
        { name: "pacification", number: 716 },
        { name: "meditation", number: 717 },
        { name: "submission", number: 718 },
        { name: "combatant", number: 719 },
        { name: "arms", number: 720 },
        { name: "arena", number: 721 },
      ],
      "results of action": [
        { name: "non-completion", number: 722 },
        { name: "success", number: 723 },
        { name: "failure", number: 724 },
        { name: "trophy", number: 725 },
        { name: "prosperity", number: 726 },
        { name: "adversity", number: 727 },
        { name: "mediocrity", number: 728 },
      ],
      general: [
        { name: "authority", number: 729 },
        { name: "laxity", number: 730 },
        { name: "severity", number: 731 },
        { name: "lenity", number: 732 },
        { name: "command", number: 733 },
        { name: "disobedience", number: 734 },
        { name: "compulsion", number: 735 },
        { name: "master", number: 736 },
        { name: "servant", number: 737 },
        { name: "sceptre", number: 738 },
        { name: "freedom", number: 739 },
        { name: "subjection", number: 740 },
        { name: "liberation", number: 741 },
        { name: "restraint", number: 742 },
        { name: "prison", number: 743 },
        { name: "keeper", number: 744 },
        { name: "prisoner", number: 745 },
        { name: "commisision", number: 746 },
        { name: "abrogation", number: 747 },
        { name: "resignation", number: 748 },
        { name: "consignee", number: 749 },
        { name: "deputy", number: 750 },
      ],
      special: [
        { name: "permission", number: 751 },
        { name: "prohibition", number: 752 },
        { name: "consent", number: 753 },
        { name: "offer", number: 754 },
        { name: "refusal", number: 755 },
        { name: "request", number: 756 },
        { name: "depreciation", number: 757 },
        { name: "petitioner", number: 758 },
      ],
      conditional: [
        { name: "promise", number: 759 },
        { name: "release", number: 760 },
        { name: "compact", number: 761 },
        { name: "condition", number: 762 },
        { name: "security", number: 763 },
        { name: "observance", number: 764 },
        { name: "non-observance", number: 765 },
        { name: "compromise", number: 766 },
      ],
      "possessive relations": [
        { name: "acquisition", number: 767 },
        { name: "loss", number: 768 },
        { name: "possession", number: 769 },
        { name: "exemption", number: 770 },
        { name: "participation", number: 771 },
        { name: "possessor", number: 772 },
        { name: "property", number: 773 },
        { name: "retention", number: 774 },
        { name: "relinquishments", number: 775 },
        { name: "transfer", number: 776 },
        { name: "giving", number: 777 },
        { name: "receiving", number: 778 },
        { name: "apportionment", number: 779 },
        { name: "lending", number: 780 },
        { name: "borrowing", number: 781 },
        { name: "taking", number: 782 },
        { name: "restitution", number: 783 },
        { name: "stealing", number: 784 },
        { name: "thief", number: 785 },
        { name: "booty", number: 786 },
        { name: "barter", number: 787 },
        { name: "purchase", number: 788 },
        { name: "sale", number: 789 },
        { name: "merchant", number: 790 },
        { name: "merchandise", number: 791 },
        { name: "mart", number: 792 },
        { name: "money", number: 793 },
        { name: "treasurer", number: 794 },
        { name: "treasury", number: 795 },
        { name: "wealth", number: 796 },
        { name: "poverty", number: 797 },
        { name: "credit", number: 798 },
        { name: "debt", number: 799 },
        { name: "payment", number: 800 },
        { name: "non-payment", number: 801 },
        { name: "expenditure", number: 802 },
        { name: "receipt", number: 803 },
        { name: "accounts", number: 804 },
        { name: "price", number: 805 },
        { name: "discount", number: 806 },
        { name: "dearness", number: 807 },
        { name: "cheapness", number: 808 },
        { name: "liberality", number: 809 },
        { name: "economy", number: 810 },
        { name: "prodigality", number: 811 },
        { name: "parsimony", number: 812 },
      ],
    },
  },
  Affections: {
    "affections generally": {
      "affections generally": [
        { name: "affections", number: 813 },
        { name: "feeling", number: 814 },
        { name: "sensibility", number: 815 },
        { name: "insensibility", number: 816 },
        { name: "excitation", number: 817 },
        { name: "excitability", number: 818 },
        { name: "inexcitability", number: 819 },
      ],
    },
    personal: {
      passive: [
        { name: "pleasure", number: 820 },
        { name: "pain", number: 821 },
        { name: "pleasureableness", number: 822 },
        { name: "painfulness", number: 823 },
        { name: "content", number: 824 },
        { name: "discontent", number: 825 },
        { name: "regret", number: 826 },
        { name: "relief", number: 827 },
        { name: "aggravation", number: 828 },
        { name: "cheerfulness", number: 829 },
        { name: "dejection", number: 830 },
        { name: "rejoicing", number: 831 },
        { name: "lamentation", number: 832 },
        { name: "amusement", number: 833 },
        { name: "weariness", number: 834 },
        { name: "wit", number: 835 },
        { name: "dulness", number: 836 },
        { name: "humorist", number: 837 },
      ],
      discriminative: [
        { name: "beauty", number: 838 },
        { name: "ugliness", number: 839 },
        { name: "ornament", number: 840 },
        { name: "blemish", number: 841 },
        { name: "simplicity", number: 842 },
        { name: "taste", number: 843 },
        { name: "vulgarity", number: 844 },
        { name: "fashion", number: 845 },
        { name: "ridiculousness", number: 846 },
        { name: "fop", number: 847 },
        { name: "affection", number: 848 },
        { name: "ridicule", number: 849 },
        { name: "laughing-stock", number: 850 }],
        prospective: [
        { name: "hope", number: 851 },
        { name: "hopelessness", number: 852 },
        { name: "fear", number: 853 },
        { name: "courage", number: 854 },
        { name: "cowardice", number: 855 },
        { name: "rashness", number: 856 },
        { name: "caution", number: 857 },
        { name: "desire", number: 858 },
        { name: "indifference", number: 859 },
        { name: "dislike", number: 860 },
        { name: "fastidiousness", number: 861 },
        { name: "satiety", number: 862 },
      ],
      contemplative: [
        { name: "wonder", number: 863 },
        { name: "expectations", number: 864 },
        { name: "prodigy", number: 865 }],
        extrinsive: [
        { name: "repute", number: 866 },
        { name: "disrepute", number: 867 },
        { name: "nobility", number: 868 },
        { name: "commonality", number: 869 },
        { name: "title", number: 870 },
        { name: "pride", number: 871},
          { name: "humility", number: 872 },
          { name: "vanity", number: 873 },
          { name: "modesty", number: 874 },
          { name: "ostentation", number: 875 },
          { name: "celebration", number: 876 },
          { name: "boasting", number: 877 },
          { name: "insolence", number: 878 },
          { name: "servility", number: 879 },
          { name: "blusterer", number: 880 },
      ]
    },
    sympathetic: {
      social: [
        { name: "friendship", number: 881 },
        { name: "enmity", number: 882 },
        { name: "friend", number: 883 },
        { name: "enemy", number: 884 },
        { name: "sociality", number: 885 },
        { name: "seclusion", number: 886 },
        { name: "courtesy", number: 887 },
        { name: "discourtesy", number: 888 },
        { name: "congratulation", number: 889 },
        { name: "love", number: 890 },
        { name: "hate", number: 891 },
        { name: "favourite", number: 892 },
        { name: "resentment", number: 893 },
        { name: "irascibility", number: 894 },
        { name: "sullenness", number: 895 },
        { name: "endearment", number: 896 },
        { name: "marriage", number: 897 },
        { name: "celibacy", number: 898 },
        { name: "divorce", number: 899 },
      ],
      diffusive: [
        { name: "benevolence", number: 900 },
        { name: "malevolence", number: 901 },
        { name: "malediction", number: 902 },
        { name: "threat", number: 903 },
        { name: "philanthropy", number: 904 },
        { name: "misanthropy", number: 905 },
        { name: "benefactor", number: 906 },
        { name: "evil doer", number: 907 }],
        special: [
        { name: "pity", number: 908 },
        { name: "pitilessness", number: 909 },
        { name: "condolence", number: 910 }],
        retrospective: [
        { name: "gratitude", number: 911 },
        { name: "ingratitude", number: 912 },
        { name: "forgiveness", number: 913 },
        { name: "revenge", number: 914 },
        { name: "jealousy", number: 915 },
        { name: "envy", number: 916 },
      ]
    },
    moral: {
      obligations: [
        { name: "right", number: 917 },
        { name: "wrong", number: 918 },
        { name: "dueness", number: 919 },
        { name: "undueness", number: 920 },
        { name: "duty", number: 921 },
        { name: "dereliction", number: 922 },
        { name: "exemption", number: 923 }],
        sentiments: [
        { name: "respect", number: 924 },
        { name: "disrespect", number: 925 },
        { name: "contempt", number: 926 },
        { name: "approbation", number: 927 },
        { name: "disapprobation", number: 928 },
        { name: "flattery", number: 929 },
        { name: "detraction", number: 930 },
        { name: "flatterer", number: 931 },
        { name: "detractor", number: 932 },
        { name: "vindication", number: 933 },
        { name: "accusation", number: 934 },
      ],
      conditions: [
        { name: "probity", number: 935 },
        { name: "improbity", number: 936 },
        { name: "knave", number: 937 },
        { name: "disinterestedness", number: 938 },
        { name: "selfishness", number: 939 },
        { name: "virtue", number: 940 },
        { name: "vice", number: 941 },
        { name: "innocence", number: 942 },
        { name: "guilt", number: 943 },
        { name: "good man", number: 944 },
        { name: "bad man", number: 945 },
        { name: "penitence", number: 946 },
        { name: "impenitence", number: 947 },
        { name: "atonement", number: 948 }],
        practice: [
        { name: "temperance", number: 949 },
        { name: "intemperance", number: 950 },
        { name: "sensualist", number: 951 },
        { name: "asceticism", number: 952 },
        { name: "fasting", number: 953 },
        { name: "gluttony", number: 954 },
        { name: "sobriety", number: 955 },
        { name: "drunknesness", number: 956 },
        { name: "purity", number: 957 },
        { name: "impurity", number: 958 },
        { name: "libertine", number: 959 }],
        institutions: [
          { name: "legality", number: 960 },
          { name: "illegality", number: 961 },
          { name: "jurisprudence", number: 962 },
          { name: "tribunal", number: 963 },
          { name: "judge", number: 964 },
          { name: "lawyer", number: 965 },
          { name: "lawsuit", number: 966 },
          { name: "acquital", number: 967 },
          { name: "condemnation", number: 968 },
          { name: "punishment", number: 969 },
          { name: "reward", number: 970 },
          { name: "penalty", number: 971 },
          { name: "scourge", number: 972 },
      ]
    },
    religious: {
      "superhuman beings and regions": [
        { name: "deity", number: 973 },
        { name: "angel", number: 974 },
        { name: "satan", number: 975 },
        { name: "jupiter", number: 976 },
        { name: "demon", number: 977 },
        { name: "heaven", number: 978 },
        { name: "hell", number: 979 },
      ],
      doctrines: [
        { name: "theology", number: 980 },
        { name: "orthodoxy", number: 981 },
        { name: "heterodoxy", number: 982 },
        { name: "revelation", number: 983 },
        { name: "pseudo-revelation", number: 984 },
      ],
      sentiments: [
        { name: "piety", number: 985 },
        { name: "impiety", number: 986 },
        { name: "irreligion", number: 987 },
      ],
      acts: [
        { name: "worship", number: 988 },
        { name: "idolatry", number: 989 },
        { name: "sorcery", number: 990 },
        { name: "spell", number: 991 },
        { name: "sorcerer", number: 992 },
        { name: "churchdom", number: 993 },
        { name: "clergy", number: 994 },
        { name: "laity", number: 995 },
        { name: "rite", number: 996 },
        { name: "canonicals", number: 997 },
        { name: "temple", number: 998 },
      ]
    }
  },
};




export const PopulateThesaurusList = ({ selectedTerms, setSelectedTerms }) => {
  const [expandedSections, setExpandedSections] = useState({});

  const toggleSection = (section) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const toggleCheckbox = (term) => {
    setSelectedTerms((prev) => {
      const existing = prev[term.name];

      // If already exists, toggle the bool
      if (existing) {
        return {
          ...prev,
          [term.name]: {
            ...existing,
            bool: !existing.bool,
          },
        };
      }

      // If new, create with bool: true
      return {
        ...prev,
        [term.name]: {
          ...term,
          bool: true,
        },
      };
    });
  };

  return (
    <div>
      {Object.entries(thesaurusJson).map(([classification, categories]) => (
        <div key={classification} className="collapsable-thesaurus-section">
          <div
            style={{ backgroundColor: "#726a3e", padding: "5px" }}
            onClick={() => toggleSection(classification)}
            className="collapsible-thesaurus-header"
          >
            <h5>{classification}</h5>
          </div>

          {expandedSections[classification] &&
            Object.entries(categories).map(([category, domains]) => (
              <div
                style={{ margin: "10px" }}
                key={category}
                className="collapsable-thesaurus-section"
              >
                <div
                  style={{
                    backgroundColor: "#rgb(106, 106, 77)",
                    padding: "5px",
                  }}
                  onClick={() => toggleSection(category)}
                  className="collapsible-thesaurus-header"
                >
                  <h6>
                    <b>{category}</b>
                  </h6>
                </div>

                {expandedSections[category] && (
                  <div style={{ columnCount: "2" }}>
                    {Object.entries(domains).map(([domain, types]) => (
                      <div style={{ marginLeft: "10px" }} key={domain}>
                        <p>
                          <i>{domain}:</i>

                          <span>
                            {types.map((type, index) => (
                              <div style={{ marginLeft: "10px" }} key={index}>
                                <input
                                  type="checkbox"
                                  id={type.name}
                                  checked={!!selectedTerms[type.name]?.bool}
                                  onChange={() => toggleCheckbox(type)}
                                />

                                <label
                                  style={{ marginLeft: "5px" }}
                                  htmlFor={type.name}
                                >
                                  {type.name}
                                </label>
                              </div>
                            ))}
                          </span>
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
        </div>
      ))}
    </div>
  );
};
